# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

# you can delete this line if you're not using Docker
image: docker:19.03.8

# open docker daemon service, need --privileged premission
services:
- name: docker:19.03.8-dind
  # if you need use repository by http portcol, uncomment next line
  command: ["--insecure-registry=47.95.254.230:8080"]

variables:
  GIT_SSL_NO_VERIFY: "true"
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DEV_DEPLOY_ACCOUNT: "kubernet"

stages:
  - build
  - deploy

build_dev:
  stage: build
  only:
    - /^dev-.*$/
  script:
    - docker login -u ${habor_user_lab} -p ${habor_password_lab} harbor.belstardoc.com
    - echo "$env_lab" > .env
    - docker pull harbor.belstardoc.com/ssmo/adapter/jk-adapter:latest || true
    - docker build --cache-from harbor.belstardoc.com/ssmo/adapter/jk-adapter:latest -t harbor.belstardoc.com/ssmo/adapter/jk-adapter:latest .
    - docker tag harbor.belstardoc.com/ssmo/adapter/jk-adapter:latest harbor.belstardoc.com/ssmo/adapter/jk-adapter:$CI_COMMIT_REF_NAME
    - docker push harbor.belstardoc.com/ssmo/adapter/jk-adapter:latest
    - docker push harbor.belstardoc.com/ssmo/adapter/jk-adapter:$CI_COMMIT_REF_NAME

build_ali:
  stage: build
  only:
    - /^ali-.*$/
  tags:
    - KH-HK
  script:
    - docker login -u ${habor_user_lab} -p ${habor_password_lab} harbor.belstardoc.com
    - docker login -u ${habor_user_ali} -p ${habor_password_ali} 47.95.254.230:8080
    - echo "$env_ali" > .env
    - docker pull harbor.belstardoc.com/ssmo/adapter/jk-adapter:latest-ali || true
    - docker build --cache-from harbor.belstardoc.com/ssmo/adapter/jk-adapter:latest -t 47.95.254.230:8080/ssmo/adapter/jk-adapter:latest .
    - docker tag 47.95.254.230:8080/ssmo/adapter/jk-adapter:latest harbor.belstardoc.com/ssmo/adapter/jk-adapter:latest-ali
    - docker tag 47.95.254.230:8080/ssmo/adapter/jk-adapter:latest 47.95.254.230:8080/ssmo/adapter/jk-adapter:$CI_COMMIT_REF_NAME
    - docker push harbor.belstardoc.com/ssmo/adapter/jk-adapter:latest-ali
    - docker push 47.95.254.230:8080/ssmo/adapter/jk-adapter:latest
    - docker push 47.95.254.230:8080/ssmo/adapter/jk-adapter:$CI_COMMIT_REF_NAME

deploy_dev:
  stage: deploy
  only:
    - /^dev-.*$/
  when: manual
  script:
    - mkdir ~/.ssh && chmod 700 ~/.ssh
    - echo "$SSH_PRIVATE_KEY_LAB" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - apk add openssh
    - echo $k8s_lab > jk-tms-render-pt.yaml
    - sed -i -e "s/harbor.belstardoc.com\/ssmo\/adapter\/jk-adapter:latest/harbor.belstardoc.com\/ssmo\/adapter\/jk-adapter:$CI_COMMIT_REF_NAME/g" jk-tms-render-pt.yaml
    - scp -o StrictHostKeyChecking=no jk-tms-render-pt.yaml ocean@192.168.20.62:~/deploy/
    - ssh -o StrictHostKeyChecking=no ocean@192.168.20.62 "kubectl -f ~/deploy/jk-tms-render-pt.yaml apply"
    - ssh -o StrictHostKeyChecking=no ocean@192.168.20.62 "kubectl -n jk annotate deployment jk-tms-render-pt kubernetes.io/change-cause=\"image updated to $CI_COMMIT_REF_NAME\""

deploy_ali:
  stage: deploy
  only:
    - /^ali-.*$/
  tags:
    - KH-HK
  when: manual
  script:
    - mkdir ~/.ssh && chmod 700 ~/.ssh
    - echo "$SSH_PRIVATE_KEY_ALI" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - apk add openssh
    - echo "$K8S_ali" > jk-tms-render-pt.yaml
    - sed -i -e "s/172.17.12.81:8080\/ssmo\/adapter\/jk-adapter:latest/172.17.12.81:8080\/ssmo\/adapter\/jk-adapter:$CI_COMMIT_REF_NAME/g" jk-tms-render-pt.yaml
    - scp -o StrictHostKeyChecking=no jk-tms-render-pt.yaml root@39.105.186.195:~/deploy/
    - ssh -o StrictHostKeyChecking=no root@39.105.186.195 "kubectl -f ~/deploy/jk-tms-render-pt.yaml apply"
    - ssh -o StrictHostKeyChecking=no root@39.105.186.195 "kubectl -n jk annotate deployment jk-tms-render-pt kubernetes.io/change-cause=\"image updated to $CI_COMMIT_REF_NAME. $CI_COMMIT_MESSAGE.\""