# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

# you can delete this line if you're not using Docker
image: docker:19.03.5

# open docker daemon service, need --privileged premission
services:
- name: docker:19.03.5-dind
  # if you need use repository by http portcol, uncomment next line
  command: ["--insecure-registry=47.95.254.230:8080"]

variables:
  GIT_SSL_NO_VERIFY: "true"
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  namespace: "ssmo/adapter"
  appName: "storage"

before_script:
  - docker login -u $dev_harbor_user -p $dev_harbor_passwd harbor.belstardoc.com

stages:
  - build
  - deploy

dev_build:
  stage: build
  only:
    - /^dev-.*$/
  script:
    - docker build --cache-from harbor.belstardoc.com/$namespace/$appName:latest -t harbor.belstardoc.com/$namespace/$appName:$CI_COMMIT_REF_NAME .
    - docker tag harbor.belstardoc.com/$namespace/$appName:$CI_COMMIT_REF_NAME harbor.belstardoc.com/$namespace/$appName:latest
    - docker push harbor.belstardoc.com/$namespace/$appName:$CI_COMMIT_REF_NAME
    - docker push harbor.belstardoc.com/$namespace/$appName:latest
